# permissions for end users to edit syncwindows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cattage
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: syncwindow-editor-role
rules:
- apiGroups:
  - cattage.cybozu.io
  resources:
  - syncwindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cattage.cybozu.io
  resources:
  - syncwindows/status
  verbs:
  - get
